### ISSUE TITLE
Enable Unity 3D  in Ubuntu VirtualBox

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/LeQue#23]
We got Ubuntu VirtualBox running on an OSX host (https://github.com/jeff1evesque/audio-analyzer/issues/18).  Unfortunately, it is running incredibly slow.  I opened _Activity Monitor_ on my OSX to review the _%CPU_ being used, and noticed that VirtualBox VM is running anywhere between 98-106% of the CPU:

![screen shot 2014-05-25 at 9 22 41 pm](https://cloud.githubusercontent.com/assets/2907085/3078480/57140196-e474-11e3-89dd-701b9d947931.png)

The issue is that if 3D acceleration is not made active, the CPU ends up being overburdened.  So, I increased the _Video Memory_ to a full `128MB`, and checked _Enable 3D Acceleration_:

![screen shot 2014-05-25 at 8 05 27 pm](https://cloud.githubusercontent.com/assets/2907085/3078401/84e92208-e470-11e3-9883-0ac96e081f09.png)

Then, I checked to see if _Unity 3D_ is supported by running the command `/usr/lib/nux/unity_support_test -p` in terminal within the VirtualBox.  I found that my instance of Ubuntu VirtualBox does not support _Unity 3D_:

![screen shot 2014-05-25 at 9 00 17 pm](https://cloud.githubusercontent.com/assets/2907085/3078420/259bb800-e471-11e3-9bba-775ca1f6b67b.png)
- https://blogs.oracle.com/fatbloke/entry/3d_acceleration_with_ubuntu_guests

**Comment by jeff1evesque** [comment]
When I run the command `sudo apt-get install build-essential`, I get:

```
Reading package lists... Done
Building dependency tree 
Reading state information... Done
E: Couldn't find package build-essential
```

Therefore, we will try `sudo apt-get update`.  This updates the _APT_ database.
- http://ubuntuforums.org/showthread.php?t=1758328

This will require wifi to be enabled (https://github.com/jeff1evesque/audio-analyzer/issues/22) on the _Ubuntu VirtualBox_ guest in order to run the latter command, which will allow us to run following commands (specifically, the last line):

```
uname -r
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get autoremove
sudo apt-get install build-essential
```

Next, click on the _Ubuntu VirtualBox_ VM window, and select on the top menu (on the OSX host) _Devices > Insert Guest Additions CD Image... (Host +D)_:

![screen shot 2014-05-27 at 1 25 55 am](https://cloud.githubusercontent.com/assets/2907085/3087742/8f9dcfd2-e560-11e3-8aad-1880dbb05168.png)

![screen shot 2014-05-27 at 1 27 47 am](https://cloud.githubusercontent.com/assets/2907085/3087745/98831878-e560-11e3-9976-c8c2c6d4c42f.png)

This will allow the guest additions to be mounted as a virtual CD visible on the launcher (notice the CD icon on the bottom left of the system menu in Ubuntu).  Thus, we will have a `/media` directory containing the necessary file to be executed in order to install _Guest Additions_ (if it didn't automatically install):

![screen shot 2014-05-27 at 9 28 41 am](https://cloud.githubusercontent.com/assets/2907085/3091988/fd0f2582-e5a3-11e3-93de-b7815fb9b997.png)

```
cd /media/[username]/VBOX*
sudo ./VBoxLinuxAdditions.run
```

Now, edit the following file:

```
sudo pico /etc/modules
```

by adding the line `vboxvideo` at the end of the file -- so, it reads as follows:

```
loop
lp
vboxvideo
```

Restart the machine by running the command `sudo reboot`.  Next, we check again to see if Unity 3D is supported by running the command `/usr/lib/nux/unity_support_test -p` in terminal:

Finally, find the `vbox` file on the host (terminal in OSX in our case) and increase the video memory:

```
pico /Users/[username]/VirtualBox VMs/ubuntu 13.04/ubuntu 13.04 VirtualBox.vbox
```

by replacing the line:

```
<Display VRAMSize="128" monitorCount="1" accelerate3D="true" accelerate2DVideo="false"/>
```

with the following:

```
<Display VRAMSize="256" monitorCount="1" accelerate3D="true" accelerate2DVideo="false"/>
```
- http://namhuy.net/951/how-to-fix-slow-performance-ubuntu-13-04-running-in-virtualbox.html

---

**Note:** the file we attempted to edit above, `pico /Users/[username]/VirtualBox VMs/ubuntu 13.04/ubuntu 13.04 VirtualBox.vbox` has spaces in between various directory names, and the filename itself.  Therefore, it may be easier to find in the file in a GUI (i.e. _Finder_ on a mac), versus using _Terminal_.

**Comment by jeff1evesque** [comment]
The attempts above was not successful.  After some quick research, we found the file `VBoxGuestAdditions_4.3.13-93885.iso` (documented on virtualbox.org less than 41hrs ago) which will be used to install Ubuntu 14.04 _Guest Additions_ within VirtualBox.  

Now, we proceed with our past assumptions:

```
uname -r
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get autoremove
sudo apt-get install build-essential
```

Then, add the _iso_ file to the _Controller: IDE_ (Add CD/DVD Device):

![screen shot 2014-05-29 at 2 38 34 am](https://cloud.githubusercontent.com/assets/2907085/3114791/eb848010-e6fb-11e3-8b94-0b0caa45bacc.png)

Finally, click _Devices > Insert Guest Additions CD Image... (Host +D)_ (on the host) to mount this file, and execute the following commands to install the _Guest Additions_:

```
cd /media/[username]/VBOX*
sudo ./VBoxLinuxAdditions.run
```

![screen shot 2014-05-29 at 2 32 18 am](https://cloud.githubusercontent.com/assets/2907085/3114794/f3f6e7f6-e6fb-11e3-909b-1d38db80fa74.png)
- https://www.virtualbox.org/ticket/12941#comment:42

**Comment by jeff1evesque** [comment]
After implementing the last comment and performing a `sudo reboot`, we have _Unity 3D_ support working.  However, we have a lot of _OpenGL Warnings_, `libGL error: failed to load driver: vboxvideo`, and the menu-bar missing from the top and left within Ubuntu (host):

![screen shot 2014-05-29 at 7 11 31 am](https://cloud.githubusercontent.com/assets/2907085/3116905/5a812d62-e722-11e3-8e1c-b4ccc60d61d4.png)

**Comment by jeff1evesque** [comment]
We added a new _Ubuntu 14.04_ (ubuntu-14.04-desktop-amd64.iso) guest in VirtualBox (deleting all previous guest instances), and made sure not to do any initial updates while being connected to the internet:

![screen shot 2014-05-29 at 10 54 14 am](https://cloud.githubusercontent.com/assets/2907085/3119065/c3c68590-e742-11e3-8c87-915ab81a695e.png)

Immediately after installation, we shutdown _Ubuntu 14.04_ VM, and created a clone of this within VirtualBox.  Next, we mounted the _iso_ file to the Controller: IDE (Add CD/DVD Device):

![screen shot 2014-05-29 at 2 38 34 am](https://cloud.githubusercontent.com/assets/2907085/3114791/eb848010-e6fb-11e3-8b94-0b0caa45bacc.png)

and proceeded to start _Ubuntu 14.04_ guest in order to install _Guest Additions_ before any updates:

![screen shot 2014-05-29 at 5 18 22 pm](https://cloud.githubusercontent.com/assets/2907085/3123843/de2ad5d8-e776-11e3-8148-f7e1e667c7ea.png)

**Comment by jeff1evesque** [comment]
The above attempt with Ubuntu 14.04 had a similar result -- CPU being over 100%, and the system menu being missing.  It had a result very much like the following:

![screen shot 2014-05-29 at 7 11 31 am](https://cloud.githubusercontent.com/assets/2907085/3116905/5a812d62-e722-11e3-8e1c-b4ccc60d61d4.png)

**Comment by jeff1evesque** [comment]
The above issue and comments are tailored for newer versions of _VirtualBox_, and _Ubuntu_.  We will close this issue for the time being, and may refer to it in the future.

**Comment by liviubalan** [comment]
Great tutorial! If you want to enable 3D Acceleration in VirtualBox you can checkout this video tutorial: http://www.liviubalan.com/virtualbox-enable-3d-acceleration
