### ISSUE TITLE
Apache2 aliases on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/LeQue#387]
We get the following message when attempting to restart Apache2 on Ubuntu Server 14.04:

```
$ sudo /etc/init.d/apache2 restart
 * Restarting web server apache2
[Wed Jul 30 08:09:41.318127 2014] [alias:warn] [pid 3565] AH00671: The Alias directive in /etc/phpmyadmin/apache.conf at line 3 will probably never match because it overlaps an earlier Alias.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                         [ OK ]
```

**Comment by jeff1evesque** [comment]
We attempt to completely stop the server, and then start it again.  The _restart_ also works:

```
$ sudo /etc/init.d/apache2 stop
 * Stopping web server apache2
 *
$ sudo /etc/init.d/apache2 start
 * Starting web server apache2
[Wed Jul 30 08:19:35.399893 2014] [alias:warn] [pid 3933] AH00671: The Alias directive in /etc/phpmyadmin/apache.conf at line 3 will probably never match because it overlaps an earlier Alias.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
 * 
$ /etc/init.d/apache2 restart 
 * Restarting web server apache2
[Wed Jul 30 08:20:04.113062 2014] [alias:warn] [pid 3997] AH00671: The Alias directive in /etc/phpmyadmin/apache.conf at line 3 will probably never match because it overlaps an earlier Alias.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```

The corresponding `/var/log/apache2/error.log`:

> ...
> [Wed Jul 30 08:19:24.415970 2014] [mpm_prefork:notice] [pid 3566] AH00169: caught SIGTERM, shutting down
> [Wed Jul 30 08:19:35.436179 2014] [mpm_prefork:notice] [pid 3934] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.3 configured -- resuming normal operations
> [Wed Jul 30 08:19:35.436233 2014] [core:notice] [pid 3934] AH00094: Command line: '/usr/sbin/apache2'
> [Wed Jul 30 08:20:03.029293 2014] [mpm_prefork:notice] [pid 3934] AH00169: caught SIGTERM, shutting down
> [Wed Jul 30 08:20:04.151140 2014] [mpm_prefork:notice] [pid 3998] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.3 configured -- resuming normal operations
> [Wed Jul 30 08:20:04.151196 2014] [core:notice] [pid 3998] AH00094: Command line: '/usr/sbin/apache2'

**Comment by jeff1evesque** [comment]
We edit the `apache2.conf`:

```
$ cd /etc/apache2/
$ sudo pico apache2.conf
```

and added the following under _Global configuration_:

```
...
# Global configuration (edited by JL)
ServerName localhost
...
```

The `apache2.conf` file will need to be adjusted when the server has a [true identity](http://wiki.apache.org/httpd/CouldNotDetermineServerName) other than _localhost_.  This eliminates one of the previous errors, specifically:

> [Wed Jul 30 08:19:35.399893 2014] [alias:warn] [pid 3933] [pid 3933] AH00671: The Alias directive in /etc/phpmyadmin/apache.conf at line 3 will probably never match because it overlaps an earlier Alias.

Now, when we restart apache2, we only have one message displaying that needs to be removed:

```
$ sudo /etc/init.d/apache2 restart
 * Restarting web server apache2
[Wed Jul 30 08:48:12.303006 2014] [alias:warn] [pid 5457] AH00671: The Alias directive in /etc/phpmyadmin/apache.conf at line 3 will probably never match because it overlaps an earlier Alias.
```

**Comment by jeff1evesque** [comment]
We previously edited the `apache.conf` file as noted in the _README.md_ file within the _[LAMP server](https://github.com/jeff1evesque/audio-analyzer#lamp-server)_ subsection (this subsection will be removed):

> LAMP server
> 
> Recall earlier that we installed our LAMP server with phpMyAdmin. We need to modify apache2.conf file in order to access phpMyAdmin:
> 
> sudo pico /etc/apache2/apache2.conf
> 
> by adding the following to the end of the file:
> 
> Allow access to phpMyAdmin (edited by JL)
> Include /etc/phpmyadmin/apache.conf
> 
> Then, restart apache:
> 
> sudo service apache2 restart

Also, we will specifically remove the following from `apache.conf`:

```
# Allow access to phpMyAdmin (edited by JL)
Include /etc/phpmyadmin/apache.conf
```

Now, when we restart apache2, we receive no messages:

```
$ sudo pico apache2.conf
$ sudo /etc/init.d/apache2 restart
 * Restarting web server apache2                                                  [ OK ]
```

Now, we attempt to access _phpMyAdmin_, and notice we can still access it within the browser:

![phpmyadmin](https://cloud.githubusercontent.com/assets/2907085/3749352/e914a5ec-17ea-11e4-8ab5-a20c62e85233.png)

**Comment by Icalvo1** [comment]
thank you this fixed commenting out " Include /etc/phpmyadmin/apache.conf " fixed the ' AH00671 ' message I was getting
